# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

# Expose your documentation as ReDoc UI compliant
#app.redocly:
#    path: /api/doc
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.redocly }

# Expose your documentation as stoplight UI compliant
app.stoplight:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.stoplight }

# Expose your documentation as Swagger UI compliant
#app.swagger_ui:
#    path: /api/doc
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
